{
 "title": "HTTP Ping",
 "description": "HTTP Ping based Blackbox Exporter Metric Dashboard.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": "label_values(probe_http_status_code, instance)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(probe_http_status_code{region!=\"\"}, region)"
   },
   {
    "name": "ssl_expires",
    "query": "query_result(bottomk(5, min by (instance) (probe_ssl_earliest_cert_expiry) - time()))"
   }
  ]
 },
 "panels": [
  {
   "title": "general",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Ping (Simple)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "probe_duration_seconds" }
     ]
    }
   ]
  },
  {
   "title": "https://prometheus.io",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "https://prometheus.io",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 2 },
     "repeat": "region",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (phase) (probe_duration_seconds{instance=~\"https://prometheus.io\",region=~\"$region\"})\n",
       "legendFormat": "https://prometheus.io"
      },
      {
       "expr": "(1 - probe_success{instance=~\"https://prometheus.io\",region=~\"$region\"} )",
       "legendFormat": "down"
      }
     ]
    }
   ]
  },
  {
   "title": "https://www.google.com",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "https://www.google.com",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "repeat": "region",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (phase) (probe_duration_seconds{instance=~\"https://www.google.com\",region=~\"$region\"})",
       "legendFormat": "https://www.google.com"
      },
      {
       "expr": "(1- probe_success{instance=~\"https://www.google.com\"} )",
       "legendFormat": "down"
      }
     ]
    }
   ]
  }
 ]
}